version: '3.5'

services:
  project-starter-server:
    container_name: project-starter-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        APP_NAME: '@dritelabs/project-starter-server'
      # restart: on-failure
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0:5000
      DATABASE_URL: postgresql://driten:driten@postgres:5432/accounts?schema=public
      MEMCACHED_HOST: memcached:11211
      AUTHORIZATION_SERVER_ISSUER_BASE_URL: http://localhost:3000
    volumes:
      - ./packages/server:/app/packages/server
      - /app/packages/server/node_modules/
      - /app/packages/server/dist/
      - /app/node_modules/

  # project-starter-frontend:
  #   container_name: project-starter-frontend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #     args:
  #       APP_NAME: '@dritelabs/project-starter-frontend'
  #     # restart: on-failure
  #   ports:
  #     - 3000:3000
  #     - 24678:24678
  #     - 24679:24679
  #   environment:
  #     NODE_ENV: development
  #     PORT: 3000
  #     SERVER_HOST: project-starter-server:4000
  #     MEMCACHED_HOST: memcached:11211
  #     SECRET_COOKIE_PASSWORD: complex_password_at_least_32_characters_long
  #   volumes:
  #     - ./apps/project-starter-frontend:/usr/src/app/packages/project-starter-frontend/
  #     - /usr/src/app/packages/project-starter-frontend/node_modules/
  #     - /usr/src/app/packages/project-starter-frontend/.nuxt/
  #     - /usr/src/app/node_modules/

networks:
  default:
    external:
      name: drite
