{{- include "drite.secret" (list . "project-starter-frontend.secret") -}}
{{- define "project-starter-frontend.secret" -}}
data:
  SECRET_COOKIE_PASSWORD: {{ "complex_password_at_least_32_characters_long" | b64enc}}
{{- end -}}
