{{- include "accounts.secret" (list . "accounts-frontend.secret") -}}
{{- define "accounts-frontend.secret" -}}
data:
  SECRET_COOKIE_PASSWORD: {{ "complex_password_at_least_32_characters_long" | b64enc}}
{{- end -}}