{{- include "accounts.secret" (list . "accounts-server.secret") -}}
{{- define "accounts-server.secret" -}}
data:
  DATABASE_URL: {{ "postgresql://doadmin:CAmLmEgPXr8t1iPp@driten-do-user-3236715-0.b.db.ondigitalocean.com:25060/accounts?sslmode=require" | b64enc }}
{{- end -}}